### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by vieck** [vieck/Save-Dat-Money#1]
## UI
- [x] Delete dashboard and go straight to Chart Activity
- [x] Make Charts no data black
- [x] In the add data fragment, make back arrow white
- [ ] Improve edit category UI overall
## Backend
- [ ] Add popup for delete all button on Chart Activity
- [ ] **Edit Category**: delete directly after add crashes the program. Refresh index
- [ ] **Edit Category**: Tell the user which category/subcategory they are deleting
- [ ] **Add Data**: tells user to add Budget instead of value
## Database
- [x] **RealmHandler**: clean file and delete other db handler files
- [ ] **RealmHandler**:Save database file to drive or device
- [ ] **RealmHandler**:Set database data from file
- [ ] **RealmHandler**:Use concurrency for large operations?
- [ ] **RealmHandler**: Use Android Chart's built in realm
## Ideas
- [ ] **Edit Category**: make left bar scrollable or maybe slide out?
- [ ] **Add Date**: pageview indicator that scrolls too between fragments
## Settings
- [ ] Try to add bottom cancel or ok button for settings
- [ ] Add reset **all** button
